### ISSUE TITLE
Define and document: What is the meaning of each priority level?

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team-prioritization#3]
**Update:** There's already working progress about this in the following [HackMD document](https://hackmd.io/7NRRbq62TnaezW7-n15cDw) by @o0Ignition0o.

- P-high is supposed to mean that the bug gets checked in on at every weekly triage meeting, to try to ensure progress (and reassign the bug to someone new if there is something blocking the current assignee). The previous section outlined where that goes wrong.
- P-medium means “this is something we do not want to ignore, but the organizer also don’t want to think about it every week.”
- P-low means “this is going to ignored until someone complains or it gets fixed by accident”

Critical bugs ...
Examples of things we typically judge to be "critical" bugs:

* Regressions where code that used to compile no longer does
    * Mitigating conditions that may lower priority:
        * If the code should never have compiled in the first place (but if the regression affects a large number of crates, this may indicate that we need a warning period)
        * If the code in question is theoretical and considered unlikely to exist in the wild, or if it only exists in small, unmaintained packages that are not widely used
    * Once a regression has hit stable for a release or two, we typically lower the priority as well, as by hat time
* Regressions where code still compiles but does something different than it used to do (dynamic semantics have changed)
    * Mitigating conditions that may lower priority:
        * If code uses feature that is explicitly not specified (e.g. `Vec` docs state order in which it drops its elements is subject to change)
* Feature-gated features accessible without a feature gate
    * Mitigating conditions that may lower priority:
        * If the pattern is VERY unlikely
* Soundness holes where common code that should not compile actually does
    * Mitigating conditions that may lower priority:
        * Soundness holes that are difficult to trigger
        * Soundness holes that have been around for a very long time may be critical, but typically require 
* Diagnostic regressions where the diagnostic is very common and the situation very confusing
* ICEs for common scenarios or code patterns
    * Mitigating conditions that may lower priority:
        * If the code that triggers the ICE also triggers compilation errors, and those errors are emitted before the ICE
        * If the code in question makes use of unstable features, particularly if the ICE requires a feature gate

Discussion about P-critical: https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/meaning.20of.20p-critical

**Comment by spastorino** [comment]
This is WIP in https://github.com/rust-lang/rust-forge/pull/390

**Comment by kellda** [comment]
rust-lang/rust-forge#390 is now merged
