### ISSUE TITLE
traigebot: add repo information to issues/pr links

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team-prioritization#4]
We should maybe write `compiler-team#123` or `rust-lang/compiler-team#123` instead of just `#123`.

**Comment by Mark-Simulacrum** [comment]
Hm usually we can get away with using the full URL and markdown syntax; this does not work in topics on Zulip I think, but there we are already doing the right thing I think?

**Comment by spastorino** [comment]
Maybe this issue was lacking some information, right now our tool is dumping our agenda as with links to github issues always as 

```
[#13](https://github.com/rust-lang/rust/issues/13)
[#143](https://github.com/rust-lang/compiler-team/issues/143)
```

This issue is about converting that to ...

```
[rust#13](https://github.com/rust-lang/rust/issues/13)
[compiler-team#143](https://github.com/rust-lang/compiler-team/issues/143)
```

**Comment by apiraino** [comment]
@spastorino if I understand correctly this issue is about updating the [current cli triagebot](https://github.com/spastorino/triagebot/), am I correct? This looks like a pretty approachable first issue to start with, may I take it?

**Comment by spastorino** [comment]
@apiraino exactly, it is about that and please go ahead and take it :heart:.
