### ISSUE TITLE
Define and document: How does the group track issues and when to revisit?

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team-prioritization#5]
The existing `P-*` labels are fairly confusing. `P-high` in particular was meant to be "critical" issues but has wound up being used for more things and has become somewhat inactionable.

Proposal:

* (Gradually?) replace other `P` labels with `Hz` labels that identify frequency to revisit:
    * Hz-daily -- for the most critical bugs
    * Hz-weekly -- typical critical bug
    * (Maybe) Hz-release -- revisit after release
* See also [Sync on How do other working groups track priorities?](#Sync-on-How-do-other-working-groups-track-priorities)

**Comment by spastorino** [comment]
This was originally proposed by @pnkfelix.

Now I wonder if we really want to replace `P-*` labels or if we want to clearly define a Hz time to revisit each of those labels. Maybe we do need a `defer-until-release` like label anyway.

**Comment by spastorino** [comment]
More information about this and areas of the compiler that I've found around is ...

This is somewhat related to the `Define areas of the compiler` work the compiler team has been doing.

The async-await working group has been making an active effort to triage and track priorities. The Hz- labels could also be used for this purpose, perhaps with "non-time-based" scopes. For example:

* Hz-active -- part of current "sprint", will tag the first N "medium"-like issues as active, then gradually fix those
* Hz-deferred -- issues to revisit after sprint is over, or perhaps after enough time has elapsed
* Hz-never -- issues not scheduled to be revisited (i.e., P-low)

**Comment by apiraino** [comment]
>     * (Gradually?) replace other `P` labels with `Hz` labels that identify frequency to revisit:

I (for one) am not sure a "Hz" based naming scheme would be completely beneficial to express a priority. While many are familiar and understand the parallel, I am afraid it would turn out to be needing an explaination (even as small as "Hertz express frequency, hence our labeling scheme"), and that would add a tiny amount of friction esp. to newcomers.
I think priority is priority and this is pretty straightforward. This [WIP document](https://github.com/rust-lang/rust-forge/pull/390) explains (imo) very well how they work (or are meant to work). Now, I didn't follow closely the discussion, but would it make sense to try fixing how labels are actually used?

>     * See also [Sync on How do other working groups track priorities?](#Sync-on-How-do-other-working-groups-track-priorities)

@spastorino I think this link is incorrect :thinking:

**Comment by spastorino** [comment]
As per [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/2020-07-07.20Steering.20meeting/near/203203533) closing as non actionable for now but we should keep checking this idea in the future.
