### ISSUE TITLE
Define and document our process in forge

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team-prioritization#6]
We can start with the content we have in [our Process HackMD document](https://hackmd.io/WJ0G17DHTHGgv0OW9I2PxA?view).

Note that the document may be a bit untidy and not with a perfect written english (my bad there). I'd say that if someone can read it and understand what it means we can just copy it or parts of it to forge, the things that are not clear you can write to me and we can try to write something that explains more clearly.

**Comment by spastorino** [comment]
Maybe we need to wait until we integrate everything with triagebot for real.

**Comment by spastorino** [comment]
We may also want to document a typical workflow, ideas that I got from documents ...

```
## Define and document: Typical workflow

* Issue gets filed
* Release team applies labels
    * area labels, team labels
* If bisection, mcve needed:
    * tag with needs-bisection, needs-mcve
    * cc "Cleanup crew"
* In some cases:
    * directly prioritize or send to the right place if it seems clear
    * otherwise, nominate for compiler team meeting
* Release team nominates for compiler team to further process
    * also cc folks to bisect 
    * (usually ICE), usually includes needs-bisection and needs-mcve
* Compiler team triage group analyzes and figures out which things apply
    * Critical bugs:
        * Tag with P-critical
    * Needs team discussion:
    * Delegation:
        * Should we cc
```

**Comment by spastorino** [comment]
After doing this, as we will be documenting things from our working group we would want also to kill our [Master HackMD Document](https://hackmd.io/P3yvagSSS7yAI2QxhLfPtQ?both) and use forge for that purpose instead.

**Comment by apiraino** [comment]
This seems to require an initial amount of sifting through sparse existing documentation and put it into a coherent form, correct? I could try gathering these resources and throwing them at this repo into a PR to then iterate and refine. Make sense? That would help me better understanding the process itself :-)

**Comment by spastorino** [comment]
@apiraino definitely, :heart:

**Comment by spastorino** [comment]
Closed by https://github.com/rust-lang/rust-forge/pull/395
