### ISSUE TITLE
Add to-announce to FCPs once they are finished

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team-prioritization#9]
We would need to automatically add a `to-announce` label to finished FCPs on rust repo, so our prioritization cli can pick them up to make the announcements of them. Otherwise we would get this [full list of finished FCPs](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aall+label%3Afinished-final-comment-period).

**Comment by LeSeulArtichaut** [comment]
There is no `to-announce` label in the `rust-lang/rust` repo. Once we’ve created it, we should be able to use triagebot’s autolabeling system to add it whenever the `finished-final-comment-period` label is added.

**Comment by spastorino** [comment]
@LeSeulArtichaut yeah I know, adding the label would be step 1 :). Going to ask Niko and/or Felix about this.

**Comment by spastorino** [comment]
@LeSeulArtichaut I've talked to Niko, we agreed on this and just created the label.

**Comment by LeSeulArtichaut** [comment]
@spastorino Should we add it on all finished FCPs or only on T-compiler ones?

**Comment by spastorino** [comment]
If they are properly tagged I'd say only `T-compiler` ones.

**Comment by spastorino** [comment]
I've implemented this in triagebot and rfcbot.

https://github.com/rust-lang/triagebot/pull/762
https://github.com/rust-lang/rfcbot-rs/pull/289
